# Use postgres/example user/password credentials
version: '3.1'

services:
  mysql:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_DB: trt
      POSTGRES_PASSWORD: example

